import type { Metadata } from 'next'
import LegalPage from '@/components/marketing/LegalPage'

export const dynamic = 'force-static'

export const metadata: Metadata = {
  title: 'Privacy Policy — Absolutely Butter',
  description: 'What Absolutely Butter collects and why.',
  alternates: { canonical: '/privacy' },
  robots: { index: false },
}

export default function PrivacyPage() {
  return (
    <LegalPage title="Privacy Policy" lastUpdated="September 2026">
      <p>
        This is a placeholder privacy policy for the Absolutely Butter beta. It
        describes current practice in plain terms; a full policy will replace it
        before general availability.
      </p>

      <h2>What we collect</h2>
      <p>
        <strong>Your account.</strong> Email address and a hashed password, held
        by our authentication provider (Supabase).
      </p>
      <p>
        <strong>Billing.</strong> Payment details are handled entirely by Stripe.
        We store a customer ID and subscription status — never card numbers.
      </p>
      <p>
        <strong>Experiment data.</strong> For each experiment we store four
        counters per variant (impressions and conversions) and per-visitor
        session identifiers generated by the SDK. We do not collect visitor names,
        emails, IP addresses, or any content from your pages.
      </p>
      <p>
        <strong>Product analytics.</strong> Standard server logs for the
        dashboard and API. No third-party advertising or tracking scripts run on
        this site.
      </p>

      <h2>How we use it</h2>
      <p>
        To run your experiments, compute their statistics, bill your
        subscription, and keep the service secure and working. We do not sell data
        or share it with third parties except the processors named above
        (Supabase, Stripe) acting on our behalf.
      </p>

      <h2>Your choices</h2>
      <p>
        You can export or delete your experiments from the dashboard, and close
        your account at any time, which removes your profile and experiment data.
      </p>

      <h2>Contact</h2>
      <p>
        Questions about privacy: <a href="mailto:privacy@absolutely-butter.com">privacy@absolutely-butter.com</a>.
      </p>
    </LegalPage>
  )
}
